POST http://localhost:3000/api/movies
Content-Type: application/json

{
  "title": "Cidade ",
  "synopsis": "A história do crescimento do Rio de Janeiro.",
  "genre": "Crime",
  "releaseDate": "2002-08-30"
}
###

GET http://localhost:3000/api/movies
###

PATCH http://localhost:3000/api/movies/1
Content-Type: application/json

{
  "genre": "Sci-Fi"
}
###

DELETE http://localhost:3000/api/movies/4

###