@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6InVzZXIiLCJpYXQiOjE3Nzk3NTU2NzEsImV4cCI6MTc3OTg0MjA3MX0._puGBCDUf_WMrgACF4t4mAMrABr8zlmlfJ0GOCnTPJc

POST http://localhost:3000/api/movie-status
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "movieId": 1,
  "status": "njdfjhsdf"
}
###

GET http://localhost:3000/api/movie-status
###

PATCH http://localhost:3000/api/movie-status/2
Content-Type: application/json

{
  "status": "aguardando_lancamento"
}
###

DELETE http://localhost:3000/api/movie-status/2

###


