POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "name": "Jose",
  "email": "j@email.com",
  "password": "1234"
}
###

GET http://localhost:3000/api/usuarios
###

DELETE http://localhost:3000/api/usuarios/5
###

PATCH http://localhost:3000/api/usuarios/7
Content-Type: application/json

{
    "password": "1234"
}
###

//****************** LOGIN ******************
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "j@email.com",
  "password": "1234"
}

###

GET /api/usuarios?page=2&limit=3

###
